apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vgo9654y6-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c4bb3e3f07.ezm0.p3.openshiftapps.com/rhtap/rhtap-qe:d43a53bee597b872092d81bb0a8a9d629c8e3fa0@sha256:860ef7ede94e11c2089f1ce3f0a13fc5eedc64c584b8892a63607182db524d25
          name: container-image
