apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vgo9654y6-java-quarkus
  janus-idp.io/tekton: vgo9654y6-java-quarkus
  backstage.io/kubernetes-id: vgo9654y6-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vgo9654y6-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
